// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuqavetwmewaapayaruy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1cWF2ZXR3bWV3YWFwYXlhcnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTQ5ODksImV4cCI6MjA2Mzg5MDk4OX0.lVBkX7ik2GD9ohvyLqn5YfI-4PnjXi7rQ7GfSCb2Q6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);