name: Database Read Check

on:
  schedule:
    # Runs every 5 days at 2:00 AM UTC
    - cron: '0 2 */5 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  database-read:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --only=production
      
      - name: Run database read check
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node .github/scripts/database-read.js
      
      - name: Report status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Database read check completed successfully"
          else
            echo "❌ Database read check failed"
          fi